name: Preview Deploy

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.8]

    steps:
      - uses: actions/checkout@v3

      - name: GitHub Refs
        uses: rlespinasse/github-slug-action@v3.x

      - name: Cache Node Modules & NextJS Cache
        id: cache-node-modules-next
        uses: actions/cache@v3
        with:
          path: |
            "**/node_modules/"
            "**/.next/cache/"
            "node_modules/"
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/frontend/*.js') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install SST dependencies
        if: steps.cache-node-modules-next.outputs.cache-hit != 'true'
        run: npm install
        working-directory: ./

      - name: Install NextJS dependencies
        run: npm install
        working-directory: ./frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Serverless Stack Deploy
        id: serverless-stack-deploy
        run: npx sst deploy --stage ${{ env.GITHUB_REF_NAME_SLUG }}

      #- name: Test
      #  run: yarn turbo run test
